web:
  build: ./dockerfile_nodejs
  ports:
    - "3000:3000"
  volumes:
     - ./myapp:/home/myapp
  links:
    - "db:mongo"
  tty: true
db:
  image: mongo
  volumes_from:
    - dataonly
dataonly:
  build: ./dockerfile_BusyBox
  tty: true
