web:
  build: ./dockerfile_ubuntu_nodejs
  ports:
    - "3000:3000"
    - "8000:8000"
    - "49100:22"
    - "127.0.0.1:8001:8001"
  expose:
    - "3000"
    - "8000"
  links:
    - "db:mongo"
  tty: true
db:
  image: mongo
  volumes_from:
    - dataonly
dataonly:
  build: ./dockerfile_BusyBox
  tty: true
